"""empty message

Revision ID: 15687211b362
Revises: 
Create Date: 2023-11-12 12:48:30.306072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15687211b362'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('selected_avatar', sa.String(length=200), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('health', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_health', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_user', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('users_habits_array', sa.PickleType(), nullable=True),
    sa.Column('users_clicked_habits', sa.PickleType(), nullable=True),
    sa.Column('users_dailies_array', sa.PickleType(), nullable=True),
    sa.Column('users_clicked_dailies', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dailies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('repeat_time_frame', sa.String(), nullable=True),
    sa.Column('repeat_quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('untouched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('alignment', sa.Boolean(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('reset_rate', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('untouched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habits')
    op.drop_table('dailies')
    op.drop_table('users')
    # ### end Alembic commands ###
